### PR TITLE
Introduce some type definitions

### PR DESCRIPTION
**Pull request by vmwxiong**
Quick pass at some basic type defs. Not exhaustive, and would not be surprised if it has inaccuracies!

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

Fixes: https://github.com/playcanvas/playcanvas-tween/issues/24

### CODE REVIEW

**Comment by yaustar** [comment]
@willeastcott Does the package.json need to be updated to include the definition file?

**Comment by willeastcott** [comment]
We never published this repo to NPM, so it's not really necessary.

**Comment by willeastcott** [comment]
@vmwxiong Can you please apply 4 space indentation to this file please.

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
Nice, thanks!! 🙌

**Pull request merged**
