### PR TITLE
This adds an app.addTweenManager() method

### LINKED ISSUE #6: Loading this library before creating an app
Creating an app may not always happen before loading `playcanvas-tween`. In those cases, the [integration of the library with the app](https://github.com/playcanvas/playcanvas-tween/blob/master/tween.js#L676-L701) does not happen, which is problematic. I am dealing with a project that has PlayCanvas for only a part of the full project, as it uses simple DOM UI on the outside before entering the game world. In that case, I run into this race condition.

It would be so nice if this tween library could automatically register itself on any new app *when* the app gets created, just like how PlayCanvas already does actions like this *when* things are available (asset loading, etc).

Alternatively, perhaps expose the integration in some way so I can trigger it myself?

### PR DESCRIPTION
**Pull request by ronkorving**
This is useful when creating multiple apps, or when creating apps after having loaded this tween library.

Fixes #6

### CODE REVIEW

**Comment by ronkorving** [comment]
cc @willeastcott @daredevildave 

Just a friendly poke since I notice this is the first PR ever made to this repo, and you may not get a notification when a PR is opened? :)

**Comment by willeastcott** [comment]
Thanks a lot for looking into fixing that issue @ronkorving. But I wasn't involved in the development of this repo so I'm not really a good person to review your PR. I think @vkalpias is a better option - but just so you know, he's very busy on a project just at the moment, which probably explains the delay in you getting a response.

**Comment by ronkorving** [comment]
@willeastcott @vkalpias Understood. Looking forward to some feedback though :) Even if merging takes a bit longer.

**Comment by vkalpias** [comment]
Hi sorry for the delay. Thanks for the PR - We generally try to keep APIs as minimal as possible - this seems to add a function to basically do this? 

`application._tweenManager = new pc.TweenManager(application);`

**Comment by daredevildave** [comment]
I think this looks fine. Makes sense to have a function which can be called later to initialize the tween manager

**Comment by ronkorving** [comment]
@vkalpias Yeah exactly. It would've been more playcanvas-y if we were able to do:

```js
pc.on('app', (app) => {
  app._tweenManager = new pc.TweenManager(app);
});
```

But there's no event to listen for when new apps are created. So this has to be done manually if it needs to be done for any app after the first. An alternative is to not expose a function at all (which I'm not really a fan of, but sure), but we would still need to move all the other code that this PR moves, in order to always expand the pc.Entity prototype. That part should not depend on there being an application yet or not.

**Comment by vkalpias** [comment]
That's fine I think we'll merge this

**Comment by daredevildave** [comment]
Looks good to me. Can you complete the PlayCanvas Contributor License Agreement? https://docs.google.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/edit

Thanks

**Comment by ronkorving** [comment]
Done 👍

**Pull request merged**
